######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 19 15:18:05 2021
######################################################################

INCLUDEPATH+=../CXX_TOOLS_LIB/
LIBS+=-L../libs -lcxx_tools
CONFIG=release
DESTDIR=../libs
OBJECTS_DIR=intout
TEMPLATE = lib
TARGET = cbm_state
DEPENDPATH += . \
              CBMStateInclude/interfaces \
              CBMStateInclude/params \
              CBMStateInclude/state \
              src/interfaces \
              src/params \
              src/state
INCLUDEPATH += . \
               CBMStateInclude/interfaces \
               CBMStateInclude/params \
               CBMStateInclude/state

# Input
HEADERS += CBMStateInclude/interfaces/cbmstate.h \
           CBMStateInclude/interfaces/cbmstatex2grgodecouple.h \
           CBMStateInclude/interfaces/iactivityparams.h \
           CBMStateInclude/interfaces/iconnectivityparams.h \
           CBMStateInclude/interfaces/iinnetconstate.h \
           CBMStateInclude/interfaces/imzoneactstate.h \
           CBMStateInclude/params/activityparams.h \
           CBMStateInclude/params/connectivityparams.h \
           CBMStateInclude/state/innetactivitystate.h \
           CBMStateInclude/state/innetconnectivitystate.h \
           CBMStateInclude/state/innetconstateggialtcon.h \
           CBMStateInclude/state/mzoneactivitystate.h \
           CBMStateInclude/state/mzoneconnectivitystate.h
SOURCES += src/interfaces/cbmstate.cpp \
           src/interfaces/cbmstatex2grgodecouple.cpp \
           src/interfaces/iactivityparams.cpp \
           src/interfaces/iconnectivityparams.cpp \
           src/interfaces/iinnetconstate.cpp \
           src/interfaces/imzoneactstate.cpp \
           src/params/activityparams.cpp \
           src/params/connectivityparams.cpp \
           src/state/innetactivitystate.cpp \
           src/state/innetconnectivitystate.cpp \
           src/state/innetconstateggialtcon.cpp \
           src/state/mzoneactivitystate.cpp \
           src/state/mzoneconnectivitystate.cpp
